---
- hosts: all
  become: false
  gather_facts: true
  vars_files:
      - vars.yml

  tasks:
    - name: Add VBox apt keys
      become: true
      apt_key:
          url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
          state: present
    - name: Add VirtualBox repository
      become: true
      apt_repository:
          repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
          filename: vbox
    - name: Add Docker apt keys
      become: true
      apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
    - name: Add Brave apt key
      become: true
      get_url:
          url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
          dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
          owner: root
          group: root
          mode: 0644
    - name: Add WineHQ apt key
      become: true
      get_url:
          url: https://dl.winehq.org/wine-builds/winehq.key
          dest: /usr/share/keyrings/winehq-archive.key
          owner: root
          group: root
          mode: 0644
      tags:
          - wine
    - name: Download Signal apt key
      become: true
      get_url:
        url: https://updates.signal.org/desktop/apt/keys.asc
        dest: ~/signal_keys.asc
      tags:
        - messengers
    - name: Add Signal apt key
      become: true
      shell:
        cmd: "cat ~/signal_keys.asc | gpg --dearmor > /usr/share/keyrings/signal-desktop-keyring.gpg"
      tags:
        - messengers
    - name: Cleanup Signal key download
      become: true
      file:
        path: ~/signal_keys.asc
        state: absent
    - name: Add Docker repository
      become: true
      apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
          filename: docker
    - name: Add Brave repository
      become: true
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
        filename: brave
    - name: Add WineHQ repository
      become: true
      get_url:
          url: "https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources"
          dest: /etc/apt/sources.list.d/winehq.sources
      tags:
          - wine
    - name: Add Signal repository
      become: true
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main"
        filename: signal
      tags:
        - messengers
    - name: Enable i386 architecture
      become: true
      command: dpkg --add-architecture i386
      tags:
          - wine

    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
      tags:
        - long
        - minimal
    - name: Install packages
      become: true
      apt:
        name: "{{ packages }}"
        state: latest
      tags:
        - minimal

    - name: Create source directory structure
      file:
        name: "~/source/private"
        state: directory
      tags:
        - minimal

    - name: Check if oh-my-zsh repo already exists
      stat: path=~/.oh-my-zsh
      register: ohmyzsh
      tags:
        - minimal
    - name: Clone oh-my-zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh
        dest: ~/.oh-my-zsh
      when: not ohmyzsh.stat.exists
      tags:
        - minimal

    - name: Check if vundle repo already exists
      stat: path=~/.vim/bundle/Vundle.vim
      register: vundle
      tags:
        - minimal

    - name: Create vim undo dir
      file:
          name: ~/.vim_undo
          state: directory
      tags:
        - minimal

    - name: Check if configurations repo already exists
      stat: path=~/source/private/configurations/
      register: configs
      tags:
        - minimal
    - name: Clone configurations repo
      git:
        repo: git@github.com:Venefyxatu/Configurations
        dest: "~/source/private/configurations"
        key_file: "~/.ssh/id_rsa_github"
        accept_hostkey: true
      when: not configs.stat.exists
      tags:
        - minimal

    - name: Ensure ~/.config exists
      file:
          state: directory
          name: ~/.config
      tags:
          - minimal
    - name: Create config symlinks
      file:
        state: link
        src: "~/source/private/configurations/{{ item.value.src }}"
        name: "{{ item.value.link }}"
      loop: "{{ lookup('dict', config_files ) }}"
      tags:
        - minimal

    - name: Clone Vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim
        dest: ~/.vim/bundle/Vundle.vim
      when: not vundle.stat.exists
      tags:
        - minimal

    - name: Install vim plugins
      shell: vim +PluginInstall +qall
      tags:
        - minimal

    - name: Compile YouCompleteMe
      shell: cd ~/.vim/bundle/YouCompleteMe && python3 install.py
      tags:
        - long
      tags:
        - minimal

    - name: Install ropevim
      become: true
      shell: pip3 install rope ropevim
      tags:
        - minimal

    - name: Link scripts
      become: true
      file:
          state: link
          src: "~{{ username }}/source/private/configurations/scripts/{{ item }}"
          dest: "/usr/bin/{{ item }}"
          mode: 0755
      with_items:
        - runonce.sh
        - sysbacklight

    - name: Copy sudoers
      become: true
      become: true
      shell:
        cmd: "cp ~{{ username }}/source/private/configurations/sudoers/backlight /etc/sudoers.d/backlight && chown root:root /etc/sudoers.d/backlight && chmod 0644 /etc/sudoers.d/backlight"

    - name: Set user shell
      become: true
      user:
        name: "{{ username }}"
        shell: /usr/bin/zsh
      tags:
        - minimal
    - name: Add user to groups
      become: true
      user:
          name: "{{ username }}"
          append: yes
          groups:
            - docker
            - erik
            - adm
            - cdrom
            - sudo
            - dip
            - plugdev
            - lpadmin
      tags:
        - minimal

    - name: Install Wine
      become: true
      apt:
        name:
          - "winehq-staging"
          - "winbind"
        state: latest
      tags:
          - wine
    - name: Install winetricks
      become: true
      get_url:
          url: "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks"
          dest: /usr/local/bin/
          mode: 0755
      tags:
          - wine
    - name: Configure XDM
      become: true
      copy:
          src: files/xdm/
          dest: /etc/X11/xdm/
      tags:
          - xdm
    - name: Create backgrounds folder
      become: true
      file:
        name: /usr/local/share/backgrounds/
        state: directory
      tags:
          - xdm
    - name: Download discord
      get_url:
        url: https://discord.com/api/download?platform=linux&format=deb
        dest: ~/Downloads/discord.deb
      tags:
        - messengers
    - name: Install discord
      become: true
      apt:
        deb: "~{{ username }}/Downloads/discord.deb"
