---
- hosts: all
  become: false
  gather_facts: true
  vars_files:
      - vars.yml

  tasks:
    - name: Add awesomewm PPA
      become: true
      apt_repository:
        repo: ppa:klaus-vormweg/awesome
        state: present
        filename: awesome-wm
    - name: Add Vagrant PPA
      become: true
      apt_repository:
          repo: ppa:tiagohillebrandt/vagrant
          filename: vagrant
    - name: Add VBox apt keys
      become: true
      apt_key:
          url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
          state: present
    - name: Add VirtualBox repository
      become: true
      apt_repository:
          repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
          filename: vbox

    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
      tags:
        - long
    - name: Install packages
      become: true
      apt:
        name: "{{ packages }}"
        state: latest
    - name: Download & install Chrome
      become: true
      apt:
          deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      tags:
        - long

    - name: Create source directory structure
      file:
        name: "~/source/private"
        state: directory

    - name: Check if configrations repo already exists
      stat: path=~/source/private/configurations/
      register: configs
    - name: Clone configurations repo
      git:
        repo: git@github.com:Venefyxatu/Configurations
        dest: "~/source/private/configurations"
        key_file: "~/.ssh/id_rsa_github"
      when: not configs.stat.exists

    - name: Create config symlinks
      file:
        state: link
        src: "~/source/private/configurations/{{ item.value.src }}"
        name: "{{ item.value.link }}"
      loop: "{{ lookup('dict', config_files ) }}"

    - name: Check if oh-my-zsh repo already exists
      stat: path=~/.oh-my-zsh
      register: ohmyzsh
    - name: Clone oh-my-zsh
      git:
        repo: git@github.com:ohmyzsh/ohmyzsh
        dest: ~/.oh-my-zsh
      when: not ohmyzsh.stat.exists

    - name: Check if vundle repo already exists
      stat: path=~/.vim/bundle/Vundle.vim
      register: vundle

    - name: Clone Vundle
      git:
        repo: git@github.com:VundleVim/Vundle.vim
        dest: ~/.vim/bundle/Vundle.vim
      when: not vundle.stat.exists

    - name: Create vim undo dir
      file:
          name: ~/.vim_undo
          state: directory

    - name: Install vim plugins
      shell: vim +PluginInstall +qall

    - name: Compile YouCompleteMe
      shell: cd ~/.vim/bundle/YouCompleteMe && python3 install.py
      tags:
        - long

    - name: Install ropevim
      become: true
      shell: pip3 install rope ropevim

    - name: Link runonce script
      become: true
      file:
          state: link
          src: ~/source/private/configurations/scripts/runonce.sh
          dest: /usr/bin/runonce.sh
          mode: 0755

    - name: Set user shell
      become: true
      user:
        name: "{{ username }}"
        shell: /usr/bin/zsh
