---
- hosts: all
  become: false
  gather_facts: true
  vars_files:
      - vars.yml

  tasks:
    - name: Add Vagrant PPA
      become: true
      apt_repository:
          repo: ppa:tiagohillebrandt/vagrant
          filename: vagrant
    - name: Add VBox apt keys
      become: true
      apt_key:
          url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
          state: present
    - name: Add VirtualBox repository
      become: true
      apt_repository:
          repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
          filename: vbox
    - name: Add Docker apt keys
      become: true
      apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
    - name: Add Docker repository
      become: true
      apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
          filename: docker

    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
      tags:
        - long
        - minimal
    - name: Install packages
      become: true
      apt:
        name: "{{ packages }}"
        state: latest
      tags:
        - minimal
    - name: Download & install Chrome
      become: true
      apt:
          deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      tags:
        - long

    - name: Create source directory structure
      file:
        name: "~/source/private"
        state: directory
      tags:
        - minimal

    - name: Check if oh-my-zsh repo already exists
      stat: path=~/.oh-my-zsh
      register: ohmyzsh
      tags:
        - minimal
    - name: Clone oh-my-zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh
        dest: ~/.oh-my-zsh
      when: not ohmyzsh.stat.exists
      tags:
        - minimal

    - name: Check if vundle repo already exists
      stat: path=~/.vim/bundle/Vundle.vim
      register: vundle
      tags:
        - minimal

    - name: Create vim undo dir
      file:
          name: ~/.vim_undo
          state: directory
      tags:
        - minimal


    - name: Check if configrations repo already exists
      stat: path=~/source/private/configurations/
      register: configs
      tags:
        - minimal
    - name: Clone configurations repo
      git:
        repo: git@github.com:Venefyxatu/Configurations
        dest: "~/source/private/configurations"
        key_file: "~/.ssh/id_rsa_github"
        accept_hostkey: true
      when: not configs.stat.exists
      tags:
        - minimal

    - name: Create config symlinks
      file:
        state: link
        src: "~/source/private/configurations/{{ item.value.src }}"
        name: "{{ item.value.link }}"
      loop: "{{ lookup('dict', config_files ) }}"
      tags:
        - minimal

    - name: Clone Vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim
        dest: ~/.vim/bundle/Vundle.vim
      when: not vundle.stat.exists
      tags:
        - minimal

    - name: Install vim plugins
      shell: vim +PluginInstall +qall
      tags:
        - minimal

    - name: Compile YouCompleteMe
      shell: cd ~/.vim/bundle/YouCompleteMe && python3 install.py
      tags:
        - long
      tags:
        - minimal

    - name: Install ropevim
      become: true
      shell: pip3 install rope ropevim
      tags:
        - minimal

    - name: Link runonce script
      become: true
      file:
          state: link
          src: "~{{ username }}/source/private/configurations/scripts/runonce.sh"
          dest: /usr/bin/runonce.sh
          mode: 0755

    - name: Set user shell
      become: true
      user:
        name: "{{ username }}"
        shell: /usr/bin/zsh
      tags:
        - minimal
    - name: Add user to groups
      become: true
      user:
          name: "{{ username }}"
          append: yes
          groups:
            - docker
            - erik
            - adm
            - cdrom
            - sudo
            - dip
            - plugdev
            - lpadmin
            - sambashare
      tags:
        - minimal
